name: Update

on:
  schedule:
    - cron: "17 4 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AUR_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Run a one-line script
        run: |
          # Clone the repo
          git clone ssh://aur@aur.archlinux.org/aws-cli-v2-bin.git
          cd aws-cli-v2-bin

          VERSION=$(git ls-remote --tags https://github.com/aws/aws-cli | awk '{print $2}' | cut -d/ -f3 | grep -v "\^{}" | sort -V | tail -n1)

          # Update version
          sed -i -e "s/^pkgver=.*$/pkgver=${VERSION}/" PKGBUILD

          # Generate integrity
          fn="awscli-exe-linux-x86_64-${VERSION}.zip"
          url="https://awscli.amazonaws.com/${fn}"
          wget -nv "$url"
          sum=$(sha256sum "$fn" | awk '{print $1}')
          rm "$fn"

          # Update integrity
          sed -i -e "s/^sha256sums=.*$/sha256sums=('${sum}')/" PKGBUILD

          # Update .SRCINFO
          sed -i -e "s/pkgver =.*$/pkgver = ${VERSION}/" .SRCINFO
          sed -i -e "s/source =.*$/source = https:\/\/awscli.amazonaws.com\/${fn}/" .SRCINFO
          sed -i -e "s/sha256sums =.*$/sha256sums = ${sum}/" .SRCINFO

          ls ~/.ssh/

          # If we have changes...
          if [[ -n "$(git diff)" ]]; then
            # Make the commit
            git config --local user.email steve@offend.me.uk
            git config --local user.name "Steve Engledow"
            git add PKGBUILD .SRCINFO
            git commit -m "Update to ${VERSION}"

            # Push to AUR
            git status
            git log -n 10
            git push
          fi
