name: Update

on:
  schedule:
    - cron: "17 4 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AUR_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Run a one-line script
        run: |
          set -eu

          # Clone the repo
          git clone ssh://aur@aur.archlinux.org/aws-cli-v2-bin.git
          cd aws-cli-v2-bin

          VERSION=$(git ls-remote --tags https://github.com/aws/aws-cli | awk '{print $2}' | cut -d/ -f3 | grep -v "\^{}" | sort -V | tail -n1)

          # Update version
          echo "Updating to version ${VERSION}"
          sed -i -e "s/^pkgver=.*$/pkgver=${VERSION}/" PKGBUILD
          sed -i -e "s/pkgver =.*$/pkgver = ${VERSION}/" .SRCINFO

          # Generate integrity
          for arch in aarch64 x86_64; do
            echo "Updating integrity for ${arch}"

            fn="awscli-exe-linux-${arch}-${VERSION}.zip"
            url="https://awscli.amazonaws.com/${fn}"
            wget -nv "$url"
            sum=$(sha256sum "$fn" | awk '{print $1}')
            rm "$fn"

            sed -i -e "s/^sha256sums_${arch}=.*$/sha256sums_${arch}=('${sum}')/" PKGBUILD
            sed -i -e "s/sha256sums_${arch} =.*$/sha256sums_${arch} = ${sum}/" .SRCINFO
            sed -i -e "s/source_${arch} =.*$/source_${arch} = https:\/\/awscli.amazonaws.com\/${fn}/" .SRCINFO
          done

          echo "PKGBUILD:"
          cat PKGBUILD

          echo ".SRCINFO:"
          cat .SRCINFO

          if [[ -n "$(git diff)" ]]; then
            echo "We have changes"
            git config --local user.email steve@offend.me.uk
            git config --local user.name "Steve Engledow"
            git add PKGBUILD .SRCINFO
            git commit -m "Update to ${VERSION}"

            echo "Pushing to AUR"
            git status
            git log -n 10
            git push
          else
            echo "No changes"
          fi
